# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: calculator.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'calculator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63\x61lculator.proto\x12\ncalculator\"%\n\x07Numbers\x12\x0c\n\x04num1\x18\x01 \x01(\x01\x12\x0c\n\x04num2\x18\x02 \x01(\x01\"P\n\rStreamRequest\x12\x0c\n\x04\x62\x61se\x18\x01 \x01(\x01\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\x12\x11\n\toperation\x18\x03 \x01(\t\x12\x0f\n\x07operand\x18\x04 \x01(\x01\"8\n\x06Result\x12\r\n\x05value\x18\x01 \x01(\x01\x12\x11\n\toperation\x18\x02 \x01(\t\x12\x0c\n\x04step\x18\x03 \x01(\x05\x32\xa0\x02\n\nCalculator\x12.\n\x03\x41\x64\x64\x12\x13.calculator.Numbers\x1a\x12.calculator.Result\x12\x33\n\x08Subtract\x12\x13.calculator.Numbers\x1a\x12.calculator.Result\x12\x33\n\x08Multiply\x12\x13.calculator.Numbers\x1a\x12.calculator.Result\x12\x31\n\x06\x44ivide\x12\x13.calculator.Numbers\x1a\x12.calculator.Result\x12\x45\n\x12StreamCalculations\x12\x19.calculator.StreamRequest\x1a\x12.calculator.Result0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calculator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NUMBERS']._serialized_start=32
  _globals['_NUMBERS']._serialized_end=69
  _globals['_STREAMREQUEST']._serialized_start=71
  _globals['_STREAMREQUEST']._serialized_end=151
  _globals['_RESULT']._serialized_start=153
  _globals['_RESULT']._serialized_end=209
  _globals['_CALCULATOR']._serialized_start=212
  _globals['_CALCULATOR']._serialized_end=500
# @@protoc_insertion_point(module_scope)
