/**
 * @fileoverview gRPC-Web generated client stub for calculator
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.21.12
// source: calculator.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.calculator = require('./calculator_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.calculator.CalculatorClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.calculator.CalculatorPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.calculator.Numbers,
 *   !proto.calculator.Result>}
 */
const methodDescriptor_Calculator_Add = new grpc.web.MethodDescriptor(
  '/calculator.Calculator/Add',
  grpc.web.MethodType.UNARY,
  proto.calculator.Numbers,
  proto.calculator.Result,
  /**
   * @param {!proto.calculator.Numbers} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.calculator.Result.deserializeBinary
);


/**
 * @param {!proto.calculator.Numbers} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.calculator.Result)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.calculator.Result>|undefined}
 *     The XHR Node Readable Stream
 */
proto.calculator.CalculatorClient.prototype.add =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/calculator.Calculator/Add',
      request,
      metadata || {},
      methodDescriptor_Calculator_Add,
      callback);
};


/**
 * @param {!proto.calculator.Numbers} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.calculator.Result>}
 *     Promise that resolves to the response
 */
proto.calculator.CalculatorPromiseClient.prototype.add =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/calculator.Calculator/Add',
      request,
      metadata || {},
      methodDescriptor_Calculator_Add);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.calculator.Numbers,
 *   !proto.calculator.Result>}
 */
const methodDescriptor_Calculator_Subtract = new grpc.web.MethodDescriptor(
  '/calculator.Calculator/Subtract',
  grpc.web.MethodType.UNARY,
  proto.calculator.Numbers,
  proto.calculator.Result,
  /**
   * @param {!proto.calculator.Numbers} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.calculator.Result.deserializeBinary
);


/**
 * @param {!proto.calculator.Numbers} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.calculator.Result)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.calculator.Result>|undefined}
 *     The XHR Node Readable Stream
 */
proto.calculator.CalculatorClient.prototype.subtract =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/calculator.Calculator/Subtract',
      request,
      metadata || {},
      methodDescriptor_Calculator_Subtract,
      callback);
};


/**
 * @param {!proto.calculator.Numbers} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.calculator.Result>}
 *     Promise that resolves to the response
 */
proto.calculator.CalculatorPromiseClient.prototype.subtract =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/calculator.Calculator/Subtract',
      request,
      metadata || {},
      methodDescriptor_Calculator_Subtract);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.calculator.Numbers,
 *   !proto.calculator.Result>}
 */
const methodDescriptor_Calculator_Multiply = new grpc.web.MethodDescriptor(
  '/calculator.Calculator/Multiply',
  grpc.web.MethodType.UNARY,
  proto.calculator.Numbers,
  proto.calculator.Result,
  /**
   * @param {!proto.calculator.Numbers} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.calculator.Result.deserializeBinary
);


/**
 * @param {!proto.calculator.Numbers} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.calculator.Result)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.calculator.Result>|undefined}
 *     The XHR Node Readable Stream
 */
proto.calculator.CalculatorClient.prototype.multiply =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/calculator.Calculator/Multiply',
      request,
      metadata || {},
      methodDescriptor_Calculator_Multiply,
      callback);
};


/**
 * @param {!proto.calculator.Numbers} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.calculator.Result>}
 *     Promise that resolves to the response
 */
proto.calculator.CalculatorPromiseClient.prototype.multiply =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/calculator.Calculator/Multiply',
      request,
      metadata || {},
      methodDescriptor_Calculator_Multiply);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.calculator.Numbers,
 *   !proto.calculator.Result>}
 */
const methodDescriptor_Calculator_Divide = new grpc.web.MethodDescriptor(
  '/calculator.Calculator/Divide',
  grpc.web.MethodType.UNARY,
  proto.calculator.Numbers,
  proto.calculator.Result,
  /**
   * @param {!proto.calculator.Numbers} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.calculator.Result.deserializeBinary
);


/**
 * @param {!proto.calculator.Numbers} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.calculator.Result)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.calculator.Result>|undefined}
 *     The XHR Node Readable Stream
 */
proto.calculator.CalculatorClient.prototype.divide =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/calculator.Calculator/Divide',
      request,
      metadata || {},
      methodDescriptor_Calculator_Divide,
      callback);
};


/**
 * @param {!proto.calculator.Numbers} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.calculator.Result>}
 *     Promise that resolves to the response
 */
proto.calculator.CalculatorPromiseClient.prototype.divide =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/calculator.Calculator/Divide',
      request,
      metadata || {},
      methodDescriptor_Calculator_Divide);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.calculator.StreamRequest,
 *   !proto.calculator.Result>}
 */
const methodDescriptor_Calculator_StreamCalculations = new grpc.web.MethodDescriptor(
  '/calculator.Calculator/StreamCalculations',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.calculator.StreamRequest,
  proto.calculator.Result,
  /**
   * @param {!proto.calculator.StreamRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.calculator.Result.deserializeBinary
);


/**
 * @param {!proto.calculator.StreamRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.calculator.Result>}
 *     The XHR Node Readable Stream
 */
proto.calculator.CalculatorClient.prototype.streamCalculations =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/calculator.Calculator/StreamCalculations',
      request,
      metadata || {},
      methodDescriptor_Calculator_StreamCalculations);
};


/**
 * @param {!proto.calculator.StreamRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.calculator.Result>}
 *     The XHR Node Readable Stream
 */
proto.calculator.CalculatorPromiseClient.prototype.streamCalculations =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/calculator.Calculator/StreamCalculations',
      request,
      metadata || {},
      methodDescriptor_Calculator_StreamCalculations);
};


module.exports = proto.calculator;

