# ==============================
# Dockerfile - client-web (nginx)
# ==============================
FROM nginx:alpine

# Copier les fichiers HTML/JS générés dans nginx
COPY . /usr/share/nginx/html

EXPOSE 80
